### PR TITLE
Added Myself, love the idea

### PR DESCRIPTION
**Pull request by 1RedOne**
Hi I love the Idea!  I applied a filter to only my PowerShell posts, so none of my SCCM stuff will be here.

If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet PowerShell blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 PowerShell related blog posts in the last 6 months
- Blog content is my own, and is not someone elses work
- The content is not sales focused
- If the blog has mixed content (PowerShell and Personal/Non-PowerShell blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet PowerShell
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by kjacobsen** [comment]
Hi,

Build is breaking due to issues with the MVP code (see issues). I will update this and merge your PR once fixed.

**Comment by kjacobsen** [comment]
Hi,

The build will be facing issues due to some issues with the MVP support.

I also notice you are missing a } at the end of your Author's file. Can you please updated it. 

Thanks!

**Comment by kjacobsen** [comment]
MVP support has been resolved. 

Let me know when you add the missing }.

**Comment by 1RedOne** [comment]
I added the squiggle.  Do I need to make a new PR?

**Comment by kjacobsen** [comment]
Hi,

No need for a new PR, it updates it with new commits.

Seems there are still some issues with your PR. Can you ensure that you have your GitHubHandle and Position.

You have also add the IFilterMyBlogPosts interface, if you are not filtering your posts, you can leave this out.

**Review by kjacobsen — APPROVED** [review]

**Comment by kjacobsen** [comment]
Hey, all of the issues have been fixed!

**Pull request merged**
