### PR TITLE
Added JonathanMedd author

### PR DESCRIPTION
**Pull request by jonathanmedd**
Submission for http://www.jonathanmedd.net

By sending this pull request to add my blog I verify that I adhere to the Planet PowerShell blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 PowerShell related blog posts in the last 6 months
- Blog content is my own, and is not someone elses work
- The content is not sales focused
- If the blog has mixed content (PowerShell and Personal/Non-PowerShell blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet PowerShell
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by kjacobsen** [comment]
Hi @jonathanmedd 

Thanks for your submission. Could you please filter your posts to only PowerShell content.

Thanks,

**Comment by jonathanmedd** [comment]
Hi @kjacobsen 

I created a feed http://feeds.feedburner.com/JonathanMeddsBlogPowerShell which is linked to http://www.jonathanmedd.net/category/powershell so only PowerShell content will appear in the feed.

However, if you want me to create a filter that some of the other authors have then I am happy to do so.

Please let me know

Thanks

**Comment by kjacobsen** [comment]
Hi,

That makes sense. I will merge you in.

**Review by kjacobsen — APPROVED** [review]

**Comment by jonathanmedd** [comment]
Thanks :-)

**Pull request merged**
