### PR TITLE
Add Author Graham Beer

### PR DESCRIPTION
**Pull request by Graham-Beer**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet PowerShell blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 PowerShell related blog posts in the last 6 months
- Blog content is my own, and is not someone elses work
- The content is not sales focused
- If the blog has mixed content (PowerShell and Personal/Non-PowerShell blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet PowerShell
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by kjacobsen** [comment]
Hi Graham,

Do you mind recreating this pull request? Not sure what has gone on, but I can't actually see the commit where it adds your blog.

Thanks!

**Comment by Graham-Beer** [comment]
Can you try now ? I'm not sure my "Public GeoPosition Position => new GeoPosition(47.643417, -122.126083);" is correct.

Thank you @kjacobsen

**Comment by kjacobsen** [comment]
Hey, 

I see what's going on. When you raised the PR, its pointing to the wrong commit. I will create a new PR for you shortly.

**Comment by Graham-Beer** [comment]
Oh thank you @kjacobsen

**Pull request closed without merging**
