### PR TITLE
Adding Graham Beer

### PR DESCRIPTION
**Pull request by kjacobsen**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet PowerShell blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 PowerShell related blog posts in the last 6 months
- Blog content is my own, and is not someone elses work
- The content is not sales focused
- If the blog has mixed content (PowerShell and Personal/Non-PowerShell blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet PowerShell
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by kjacobsen** [comment]
New PR, based on the write branches. Unfortunately, its telling me I don't have permission to approve the PR. Might need to talk to GitHub Support.

**Comment by kjacobsen** [comment]
Hi Graham,

Can you ensure you update ```src/Firehose.Web/Firehose.Web.csproj``` to include you as an author.

Thanks!

**Comment by Graham-Beer** [comment]
Hi @kjacobsen, i've recreated my files and want to do a new pull request. Can you remove the current one and i'll submit my new one ?

**Comment by kjacobsen** [comment]
Hi @Graham-Beer,

Yes, let's close this request and I will get you to generate a new one. GitHub is quite confused about this request.

**Comment by Graham-Beer** [comment]
I have an new one to go, i can generate a new pull request with that one.

**Pull request closed without merging**
